# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: enucci <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/11/25 14:04:59 by enucci            #+#    #+#              #
#    Updated: 2025/11/25 14:05:02 by enucci           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.h

CC = gcc
CFLAGS = -Wall -Wextra -Werror
SRC = 

all:$(NAME)
$(NAME):
	$(CC) $(CFLAGS) $(SRC) -o $(NAME)

fclean:
	rm -f $(NAME)

re:fclean all

.PHONY: all fclean re
